install.packages("BiocManager", repos="http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
library(BiocManager)
BiocManager::install(c("DESeq2", "graph", "RBGL"), lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("pcalg",repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("graph", repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("MASS", repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("tictoc", repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("igraph", repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("stats", repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("kpcalg", repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("sets", repos = "http://cran.us.r-project.org", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
install.packages("https://cran.r-project.org/src/contrib/Archive/SID/SID_1.0.tar.gz", lib="/homes/shahashka/causal_discovery_via_partitioning/r_temp")
