install.packages("BiocManager", repos="http://cran.us.r-project.org")
library(BiocManager)
BiocManager::install(c("DESeq2", "graph", "RBGL"))
install.packages("pcalg",repos = "http://cran.us.r-project.org")
install.packages("graph", repos = "http://cran.us.r-project.org")
install.packages("MASS", repos = "http://cran.us.r-project.org")
install.packages("tictoc", repos = "http://cran.us.r-project.org")
install.packages("igraph", repos = "http://cran.us.r-project.org")
install.packages("stats", repos = "http://cran.us.r-project.org")
install.packages("kpcalg", repos = "http://cran.us.r-project.org")
install.packages("sets", repos = "http://cran.us.r-project.org")
install.packages("https://cran.r-project.org/src/contrib/Archive/SID/SID_1.0.tar.gz")
